#(c) Copyright Ruben Cardenes Almeida 13-9-2002
#
# Sources live in src/, object files are built into build/,
# and executables are produced in the project root.

CC      = gcc
SRC     = src
BUILD   = build
# -std=gnu89 + -Wno-implicit-function-declaration keep this 2004-era C
# building on modern clang/gcc (implicit declarations are otherwise errors).
# -ffp-contract=off disables fused multiply-add contraction: the iterative
# float solvers (e.g. laplace3D's fixed-iteration relaxation) never run to
# full convergence, so letting the compiler silently fuse a*b+c into one
# rounding step makes results depend on whether the target has hardware FMA
# (arm64 always does, x86_64 without -mfma usually doesn't) -- that alone
# was enough to move thickness3d_elipsoid's mean by >1% between a macOS/arm64
# build and GitHub Actions' ubuntu-latest/x86_64 build of identical source.
FLAGS   = -g -O2 -std=gnu89 -Wno-implicit-function-declaration -ffp-contract=off -I$(SRC)

# Header dependencies are generated by the compiler into build/*.d and included
# at the bottom of this file, rather than listed by hand on each rule. The hand
# written lists named only each unit's own header, so once headers started
# including each other (laplace2D.h -> utils.h, array_utils.h) a change to
# utils.h no longer rebuilt laplace2D.o -- and with -Wno-implicit-function-
# declaration a stale object linking against a changed signature is silent.
DEPFLAGS = -MMD -MP

# png_write.c instantiates the stb_image single-header libraries, which require
# C99 or later, so it is compiled with its own flags.
PNGFLAGS = -g -O2 -std=gnu11 -ffp-contract=off -I$(SRC)

# Executables listed in README.md
EXECUTABLES = \
	thickness2D \
	thickness2D_knee \
	thickness3D \
	laplace2D \
	laplace3D \
	poisson2D \
	compute_boundary2D \
	compute_boundary_knee3D \
	compute_boundary_cortex3D \
	generar_phantom3d_elipsoid

all: $(EXECUTABLES)

## Object files (built into build/)
$(BUILD):
	mkdir -p $(BUILD)

$(BUILD)/thickness2D.o: $(SRC)/thickness2D.c | $(BUILD)
	$(CC) $(FLAGS) $(DEPFLAGS) -c $(SRC)/thickness2D.c -o $@

$(BUILD)/thickness3D.o: $(SRC)/thickness3D.c | $(BUILD)
	$(CC) $(FLAGS) $(DEPFLAGS) -c $(SRC)/thickness3D.c -o $@

$(BUILD)/laplace2D.o: $(SRC)/laplace2D.c | $(BUILD)
	$(CC) $(FLAGS) $(DEPFLAGS) -c $(SRC)/laplace2D.c -o $@

$(BUILD)/laplace3D.o: $(SRC)/laplace3D.c | $(BUILD)
	$(CC) $(FLAGS) $(DEPFLAGS) -c $(SRC)/laplace3D.c -o $@

$(BUILD)/poisson2D.o: $(SRC)/poisson2D.c | $(BUILD)
	$(CC) $(FLAGS) $(DEPFLAGS) -c $(SRC)/poisson2D.c -o $@

$(BUILD)/io.o: $(SRC)/io.c | $(BUILD)
	$(CC) $(FLAGS) $(DEPFLAGS) -c $(SRC)/io.c -o $@

$(BUILD)/png_write.o: $(SRC)/png_write.c | $(BUILD)
	$(CC) $(PNGFLAGS) $(DEPFLAGS) -c $(SRC)/png_write.c -o $@

$(BUILD)/DToptimo3d.o: $(SRC)/DToptimo3d.c | $(BUILD)
	$(CC) $(FLAGS) $(DEPFLAGS) -c $(SRC)/DToptimo3d.c -o $@

$(BUILD)/array_utils.o: $(SRC)/array_utils.c | $(BUILD)
	$(CC) $(FLAGS) $(DEPFLAGS) -c $(SRC)/array_utils.c -o $@

$(BUILD)/utils.o: $(SRC)/utils.c | $(BUILD)
	$(CC) $(FLAGS) $(DEPFLAGS) -c $(SRC)/utils.c -o $@

$(BUILD)/compute_boundary_cortex3D.o: $(SRC)/compute_boundary_cortex3D.c | $(BUILD)
	$(CC) $(FLAGS) $(DEPFLAGS) -c $(SRC)/compute_boundary_cortex3D.c -o $@

## Executables (produced in the project root)

thickness2D: $(SRC)/thickness2Dmain.c $(BUILD)/thickness2D.o $(BUILD)/laplace2D.o $(BUILD)/png_write.o $(BUILD)/array_utils.o $(BUILD)/utils.o
	$(CC) $(FLAGS) $(DEPFLAGS) -MF $(BUILD)/$@.main.d $(SRC)/thickness2Dmain.c $(BUILD)/laplace2D.o $(BUILD)/thickness2D.o $(BUILD)/png_write.o $(BUILD)/array_utils.o $(BUILD)/utils.o -lm -o $@

thickness2D_knee: $(SRC)/thickness2Dmain_knee.c $(BUILD)/thickness2D.o $(BUILD)/laplace2D.o $(BUILD)/png_write.o $(BUILD)/utils.o
	$(CC) $(FLAGS) $(DEPFLAGS) -MF $(BUILD)/$@.main.d $(SRC)/thickness2Dmain_knee.c $(BUILD)/laplace2D.o $(BUILD)/thickness2D.o $(BUILD)/png_write.o $(BUILD)/utils.o -lm -o $@

thickness3D: $(SRC)/thickness3Dmain.c $(BUILD)/laplace3D.o $(BUILD)/thickness3D.o $(BUILD)/io.o $(BUILD)/DToptimo3d.o $(BUILD)/png_write.o $(BUILD)/array_utils.o $(BUILD)/utils.o $(BUILD)/compute_boundary_cortex3D.o
	$(CC) $(FLAGS) $(DEPFLAGS) -MF $(BUILD)/$@.main.d $(SRC)/thickness3Dmain.c $(BUILD)/laplace3D.o $(BUILD)/thickness3D.o $(BUILD)/io.o $(BUILD)/DToptimo3d.o $(BUILD)/png_write.o $(BUILD)/array_utils.o $(BUILD)/utils.o $(BUILD)/compute_boundary_cortex3D.o -lm -o $@

laplace2D: $(SRC)/laplace2Dmain.c $(BUILD)/laplace2D.o $(BUILD)/png_write.o $(BUILD)/utils.o
	$(CC) $(FLAGS) $(DEPFLAGS) -MF $(BUILD)/$@.main.d $(SRC)/laplace2Dmain.c $(BUILD)/laplace2D.o $(BUILD)/png_write.o $(BUILD)/utils.o -lm -o $@

laplace3D: $(SRC)/laplace3Dmain.c $(BUILD)/laplace3D.o $(BUILD)/png_write.o $(BUILD)/utils.o
	$(CC) $(FLAGS) $(DEPFLAGS) -MF $(BUILD)/$@.main.d $(SRC)/laplace3Dmain.c $(BUILD)/laplace3D.o $(BUILD)/png_write.o $(BUILD)/utils.o -lm -o $@

poisson2D: $(SRC)/poisson2Dmain.c $(BUILD)/poisson2D.o $(BUILD)/laplace2D.o $(BUILD)/png_write.o $(BUILD)/array_utils.o $(BUILD)/utils.o
	$(CC) $(FLAGS) $(DEPFLAGS) -MF $(BUILD)/$@.main.d $(SRC)/poisson2Dmain.c $(BUILD)/poisson2D.o $(BUILD)/laplace2D.o $(BUILD)/png_write.o $(BUILD)/array_utils.o $(BUILD)/utils.o -lm -o $@

compute_boundary2D: $(SRC)/compute_boundary2D.c $(BUILD)/io.o $(BUILD)/laplace2D.o $(BUILD)/array_utils.o $(BUILD)/utils.o
	$(CC) $(FLAGS) $(DEPFLAGS) -MF $(BUILD)/$@.main.d $(SRC)/compute_boundary2D.c $(BUILD)/laplace2D.o $(BUILD)/io.o $(BUILD)/array_utils.o $(BUILD)/utils.o -lm -o $@

compute_boundary_knee3D: $(SRC)/compute_boundary_knee3D.c $(BUILD)/io.o $(BUILD)/laplace3D.o $(BUILD)/array_utils.o $(BUILD)/utils.o
	$(CC) $(FLAGS) $(DEPFLAGS) -MF $(BUILD)/$@.main.d $(SRC)/compute_boundary_knee3D.c $(BUILD)/laplace3D.o $(BUILD)/io.o $(BUILD)/array_utils.o $(BUILD)/utils.o -lm -o $@

compute_boundary_cortex3D: $(SRC)/compute_boundary_cortex3Dmain.c $(BUILD)/io.o $(BUILD)/laplace3D.o $(BUILD)/compute_boundary_cortex3D.o $(BUILD)/array_utils.o $(BUILD)/utils.o
	$(CC) $(FLAGS) $(DEPFLAGS) -MF $(BUILD)/$@.main.d $(SRC)/compute_boundary_cortex3Dmain.c $(BUILD)/laplace3D.o $(BUILD)/io.o $(BUILD)/compute_boundary_cortex3D.o $(BUILD)/array_utils.o $(BUILD)/utils.o -lm -o $@

generar_phantom3d_elipsoid: $(SRC)/generar_phantom3d_elipsoid.c
	$(CC) $(FLAGS) $(DEPFLAGS) -MF $(BUILD)/$@.main.d $(SRC)/generar_phantom3d_elipsoid.c -o $@

## Tests

# Guards the 8-connectivity rules in utils.c: neighbours must be geometrically
# adjacent (no wrapping from column 0 to column width-1 of the next row), and
# maxcomponent2D/sizefilter2D must measure components identically.
check_adjacency: tests/check_adjacency.c $(BUILD)/laplace2D.o $(BUILD)/utils.o $(BUILD)/array_utils.o
	$(CC) $(FLAGS) $(DEPFLAGS) -MF $(BUILD)/$@.main.d tests/check_adjacency.c $(BUILD)/laplace2D.o $(BUILD)/utils.o $(BUILD)/array_utils.o -lm -o $@

clean:
	rm -f $(EXECUTABLES)
	rm -f check_adjacency
	rm -rf $(BUILD)
	rm -rf *.dSYM
	rm -f *~
	rm -f *.volf
	rm -f *.vols
	rm -f *.flt
	rm -f core

# Generated header dependencies (see DEPFLAGS above).
-include $(wildcard $(BUILD)/*.d)
